//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poyecto_Tickets_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Ticket { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public int categoria { get; set; }
        public int tipo { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Asignado { get; set; }
        public int nivel_Soporte { get; set; }
        public int status { get; set; }
        public string solucion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Nivel_Soporte Nivel_Soporte1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Categoria Categoria1 { get; set; }
    }
}
